<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/common.proto

namespace Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>common.BlockData</code>
 */
class BlockData extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated bytes data = 1;</code>
     */
    private $data;

    public function __construct() {
        \GPBMetadata\Common\Common::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated bytes data = 1;</code>
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * <code>repeated bytes data = 1;</code>
     */
    public function setData(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->data = $arr;
    }

}

