<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/common.proto

namespace Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * This is finalized block structure to be shared among the orderer and peer
 * Note that the BlockHeader chains to the previous BlockHeader, and the BlockData hash is embedded
 * in the BlockHeader.  This makes it natural and obvious that the Data is included in the hash, but
 * the Metadata is not.
 * </pre>
 *
 * Protobuf type <code>common.Block</code>
 */
class Block extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.common.BlockHeader header = 1;</code>
     */
    private $header = null;
    /**
     * <code>.common.BlockData data = 2;</code>
     */
    private $data = null;
    /**
     * <code>.common.BlockMetadata metadata = 3;</code>
     */
    private $metadata = null;

    public function __construct() {
        \GPBMetadata\Common\Common::initOnce();
        parent::__construct();
    }

    /**
     * <code>.common.BlockHeader header = 1;</code>
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * <code>.common.BlockHeader header = 1;</code>
     */
    public function setHeader(&$var)
    {
        GPBUtil::checkMessage($var, \Common\BlockHeader::class);
        $this->header = $var;
    }

    /**
     * <code>.common.BlockData data = 2;</code>
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * <code>.common.BlockData data = 2;</code>
     */
    public function setData(&$var)
    {
        GPBUtil::checkMessage($var, \Common\BlockData::class);
        $this->data = $var;
    }

    /**
     * <code>.common.BlockMetadata metadata = 3;</code>
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * <code>.common.BlockMetadata metadata = 3;</code>
     */
    public function setMetadata(&$var)
    {
        GPBUtil::checkMessage($var, \Common\BlockMetadata::class);
        $this->metadata = $var;
    }

}

