<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/configtx.proto

namespace Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>common.ConfigGroupSchema</code>
 */
class ConfigGroupSchema extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>map&lt;string, .common.ConfigGroupSchema&gt; groups = 1;</code>
     */
    private $groups;
    /**
     * <code>map&lt;string, .common.ConfigValueSchema&gt; values = 2;</code>
     */
    private $values;
    /**
     * <code>map&lt;string, .common.ConfigPolicySchema&gt; policies = 3;</code>
     */
    private $policies;

    public function __construct() {
        \GPBMetadata\Common\Configtx::initOnce();
        parent::__construct();
    }

    /**
     * <code>map&lt;string, .common.ConfigGroupSchema&gt; groups = 1;</code>
     */
    public function getGroups()
    {
        return $this->groups;
    }

    /**
     * <code>map&lt;string, .common.ConfigGroupSchema&gt; groups = 1;</code>
     */
    public function setGroups(&$var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Common\ConfigGroupSchema::class);
        $this->groups = $arr;
    }

    /**
     * <code>map&lt;string, .common.ConfigValueSchema&gt; values = 2;</code>
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * <code>map&lt;string, .common.ConfigValueSchema&gt; values = 2;</code>
     */
    public function setValues(&$var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Common\ConfigValueSchema::class);
        $this->values = $arr;
    }

    /**
     * <code>map&lt;string, .common.ConfigPolicySchema&gt; policies = 3;</code>
     */
    public function getPolicies()
    {
        return $this->policies;
    }

    /**
     * <code>map&lt;string, .common.ConfigPolicySchema&gt; policies = 3;</code>
     */
    public function setPolicies(&$var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Common\ConfigPolicySchema::class);
        $this->policies = $arr;
    }

}

