<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/common.proto

namespace Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Envelope wraps a Payload with a signature so that the message may be authenticated
 * </pre>
 *
 * Protobuf type <code>common.Envelope</code>
 */
class Envelope extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * A marshaled Payload
     * </pre>
     *
     * <code>bytes payload = 1;</code>
     */
    private $payload = '';
    /**
     * <pre>
     * A signature by the creator specified in the Payload header
     * </pre>
     *
     * <code>bytes signature = 2;</code>
     */
    private $signature = '';

    public function __construct() {
        \GPBMetadata\Common\Common::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * A marshaled Payload
     * </pre>
     *
     * <code>bytes payload = 1;</code>
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * <pre>
     * A marshaled Payload
     * </pre>
     *
     * <code>bytes payload = 1;</code>
     */
    public function setPayload($var)
    {
        GPBUtil::checkString($var, False);
        $this->payload = $var;
    }

    /**
     * <pre>
     * A signature by the creator specified in the Payload header
     * </pre>
     *
     * <code>bytes signature = 2;</code>
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * <pre>
     * A signature by the creator specified in the Payload header
     * </pre>
     *
     * <code>bytes signature = 2;</code>
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->signature = $var;
    }

}

