<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msp/msp_principal.proto

namespace Common;

/**
 * Protobuf enum <code>common.MSPRole.MSPRoleType</code>
 */
class MSPRole_MSPRoleType
{
    /**
     * <pre>
     * Represents an MSP Member
     * </pre>
     *
     * <code>MEMBER = 0;</code>
     */
    const MEMBER = 0;
    /**
     * <pre>
     * Represents an MSP Admin
     * </pre>
     *
     * <code>ADMIN = 1;</code>
     */
    const ADMIN = 1;
}

