<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/configuration.proto

namespace Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * OrdererAddresses is encoded into the configuration transaction as a configuration item of type Chain
 * with a Key of "OrdererAddresses" and a Value of OrdererAddresses as marshaled protobuf bytes
 * </pre>
 *
 * Protobuf type <code>common.OrdererAddresses</code>
 */
class OrdererAddresses extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated string addresses = 1;</code>
     */
    private $addresses;

    public function __construct() {
        \GPBMetadata\Common\Configuration::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated string addresses = 1;</code>
     */
    public function getAddresses()
    {
        return $this->addresses;
    }

    /**
     * <code>repeated string addresses = 1;</code>
     */
    public function setAddresses(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->addresses = $arr;
    }

}

