<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msp/msp_principal.proto

namespace Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * OrganizationUnit governs the organization of the Principal
 * field of a policy principal when a specific organization unity members
 * are to be defined within a policy principal.
 * </pre>
 *
 * Protobuf type <code>common.OrganizationUnit</code>
 */
class OrganizationUnit extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * MSPIdentifier represents the identifier of the MSP this organization unit
     * refers to
     * </pre>
     *
     * <code>string msp_identifier = 1;</code>
     */
    private $msp_identifier = '';
    /**
     * <pre>
     * OrganizationUnitIdentifier defines the organizational unit under the
     * MSP identified with MSPIdentifier
     * </pre>
     *
     * <code>string organizational_unit_identifier = 2;</code>
     */
    private $organizational_unit_identifier = '';
    /**
     * <pre>
     * CertifiersIdentifier is the hash of certificates chain of trust
     * related to this organizational unit
     * </pre>
     *
     * <code>bytes certifiers_identifier = 3;</code>
     */
    private $certifiers_identifier = '';

    public function __construct() {
        \GPBMetadata\Msp\MspPrincipal::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * MSPIdentifier represents the identifier of the MSP this organization unit
     * refers to
     * </pre>
     *
     * <code>string msp_identifier = 1;</code>
     */
    public function getMspIdentifier()
    {
        return $this->msp_identifier;
    }

    /**
     * <pre>
     * MSPIdentifier represents the identifier of the MSP this organization unit
     * refers to
     * </pre>
     *
     * <code>string msp_identifier = 1;</code>
     */
    public function setMspIdentifier($var)
    {
        GPBUtil::checkString($var, True);
        $this->msp_identifier = $var;
    }

    /**
     * <pre>
     * OrganizationUnitIdentifier defines the organizational unit under the
     * MSP identified with MSPIdentifier
     * </pre>
     *
     * <code>string organizational_unit_identifier = 2;</code>
     */
    public function getOrganizationalUnitIdentifier()
    {
        return $this->organizational_unit_identifier;
    }

    /**
     * <pre>
     * OrganizationUnitIdentifier defines the organizational unit under the
     * MSP identified with MSPIdentifier
     * </pre>
     *
     * <code>string organizational_unit_identifier = 2;</code>
     */
    public function setOrganizationalUnitIdentifier($var)
    {
        GPBUtil::checkString($var, True);
        $this->organizational_unit_identifier = $var;
    }

    /**
     * <pre>
     * CertifiersIdentifier is the hash of certificates chain of trust
     * related to this organizational unit
     * </pre>
     *
     * <code>bytes certifiers_identifier = 3;</code>
     */
    public function getCertifiersIdentifier()
    {
        return $this->certifiers_identifier;
    }

    /**
     * <pre>
     * CertifiersIdentifier is the hash of certificates chain of trust
     * related to this organizational unit
     * </pre>
     *
     * <code>bytes certifiers_identifier = 3;</code>
     */
    public function setCertifiersIdentifier($var)
    {
        GPBUtil::checkString($var, False);
        $this->certifiers_identifier = $var;
    }

}

