<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/policies.proto

namespace Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Policy expresses a policy which the orderer can evaluate, because there has been some desire expressed to support
 * multiple policy engines, this is typed as a oneof for now
 * </pre>
 *
 * Protobuf type <code>common.Policy</code>
 */
class Policy extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * For outside implementors, consider the first 1000 types reserved, otherwise one of PolicyType
     * </pre>
     *
     * <code>int32 type = 1;</code>
     */
    private $type = 0;
    /**
     * <code>bytes policy = 2;</code>
     */
    private $policy = '';

    public function __construct() {
        \GPBMetadata\Common\Policies::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * For outside implementors, consider the first 1000 types reserved, otherwise one of PolicyType
     * </pre>
     *
     * <code>int32 type = 1;</code>
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * <pre>
     * For outside implementors, consider the first 1000 types reserved, otherwise one of PolicyType
     * </pre>
     *
     * <code>int32 type = 1;</code>
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->type = $var;
    }

    /**
     * <code>bytes policy = 2;</code>
     */
    public function getPolicy()
    {
        return $this->policy;
    }

    /**
     * <code>bytes policy = 2;</code>
     */
    public function setPolicy($var)
    {
        GPBUtil::checkString($var, False);
        $this->policy = $var;
    }

}

