<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/policies.proto

namespace Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * SignaturePolicyEnvelope wraps a SignaturePolicy and includes a version for future enhancements
 * </pre>
 *
 * Protobuf type <code>common.SignaturePolicyEnvelope</code>
 */
class SignaturePolicyEnvelope extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 version = 1;</code>
     */
    private $version = 0;
    /**
     * <code>.common.SignaturePolicy policy = 2;</code>
     */
    private $policy = null;
    /**
     * <code>repeated .common.MSPPrincipal identities = 3;</code>
     */
    private $identities;

    public function __construct() {
        \GPBMetadata\Common\Policies::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 version = 1;</code>
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * <code>int32 version = 1;</code>
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->version = $var;
    }

    /**
     * <code>.common.SignaturePolicy policy = 2;</code>
     */
    public function getPolicy()
    {
        return $this->policy;
    }

    /**
     * <code>.common.SignaturePolicy policy = 2;</code>
     */
    public function setPolicy(&$var)
    {
        GPBUtil::checkMessage($var, \Common\SignaturePolicy::class);
        $this->policy = $var;
    }

    /**
     * <code>repeated .common.MSPPrincipal identities = 3;</code>
     */
    public function getIdentities()
    {
        return $this->identities;
    }

    /**
     * <code>repeated .common.MSPPrincipal identities = 3;</code>
     */
    public function setIdentities(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Common\MSPPrincipal::class);
        $this->identities = $arr;
    }

}

