<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/policies.proto

namespace Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>common.SignaturePolicy.NOutOf</code>
 */
class SignaturePolicy_NOutOf extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 n = 1;</code>
     */
    private $n = 0;
    /**
     * <code>repeated .common.SignaturePolicy policies = 2;</code>
     */
    private $policies;

    public function __construct() {
        \GPBMetadata\Common\Policies::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 n = 1;</code>
     */
    public function getN()
    {
        return $this->n;
    }

    /**
     * <code>int32 n = 1;</code>
     */
    public function setN($var)
    {
        GPBUtil::checkInt32($var);
        $this->n = $var;
    }

    /**
     * <code>repeated .common.SignaturePolicy policies = 2;</code>
     */
    public function getPolicies()
    {
        return $this->policies;
    }

    /**
     * <code>repeated .common.SignaturePolicy policies = 2;</code>
     */
    public function setPolicies(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Common\SignaturePolicy::class);
        $this->policies = $arr;
    }

}

