<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/chaincode_shim.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>protos.ChaincodeMessage</code>
 */
class ChaincodeMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.protos.ChaincodeMessage.Type type = 1;</code>
     */
    private $type = 0;
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     */
    private $timestamp = null;
    /**
     * <code>bytes payload = 3;</code>
     */
    private $payload = '';
    /**
     * <code>string txid = 4;</code>
     */
    private $txid = '';
    /**
     * <code>.protos.SignedProposal proposal = 5;</code>
     */
    private $proposal = null;
    /**
     * <pre>
     *event emmited by chaincode. Used only with Init or Invoke.
     * This event is then stored (currently)
     *with Block.NonHashData.TransactionResult
     * </pre>
     *
     * <code>.protos.ChaincodeEvent chaincode_event = 6;</code>
     */
    private $chaincode_event = null;

    public function __construct() {
        \GPBMetadata\Peer\ChaincodeShim::initOnce();
        parent::__construct();
    }

    /**
     * <code>.protos.ChaincodeMessage.Type type = 1;</code>
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * <code>.protos.ChaincodeMessage.Type type = 1;</code>
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Protos\ChaincodeMessage_Type::class);
        $this->type = $var;
    }

    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     */
    public function setTimestamp(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->timestamp = $var;
    }

    /**
     * <code>bytes payload = 3;</code>
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * <code>bytes payload = 3;</code>
     */
    public function setPayload($var)
    {
        GPBUtil::checkString($var, False);
        $this->payload = $var;
    }

    /**
     * <code>string txid = 4;</code>
     */
    public function getTxid()
    {
        return $this->txid;
    }

    /**
     * <code>string txid = 4;</code>
     */
    public function setTxid($var)
    {
        GPBUtil::checkString($var, True);
        $this->txid = $var;
    }

    /**
     * <code>.protos.SignedProposal proposal = 5;</code>
     */
    public function getProposal()
    {
        return $this->proposal;
    }

    /**
     * <code>.protos.SignedProposal proposal = 5;</code>
     */
    public function setProposal(&$var)
    {
        GPBUtil::checkMessage($var, \Protos\SignedProposal::class);
        $this->proposal = $var;
    }

    /**
     * <pre>
     *event emmited by chaincode. Used only with Init or Invoke.
     * This event is then stored (currently)
     *with Block.NonHashData.TransactionResult
     * </pre>
     *
     * <code>.protos.ChaincodeEvent chaincode_event = 6;</code>
     */
    public function getChaincodeEvent()
    {
        return $this->chaincode_event;
    }

    /**
     * <pre>
     *event emmited by chaincode. Used only with Init or Invoke.
     * This event is then stored (currently)
     *with Block.NonHashData.TransactionResult
     * </pre>
     *
     * <code>.protos.ChaincodeEvent chaincode_event = 6;</code>
     */
    public function setChaincodeEvent(&$var)
    {
        GPBUtil::checkMessage($var, \Protos\ChaincodeEvent::class);
        $this->chaincode_event = $var;
    }

}

