<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/transaction.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * ChaincodeActionPayload is the message to be used for the TransactionAction's
 * payload when the Header's type is set to CHAINCODE.  It carries the
 * chaincodeProposalPayload and an endorsed action to apply to the ledger.
 * </pre>
 *
 * Protobuf type <code>protos.ChaincodeActionPayload</code>
 */
class ChaincodeActionPayload extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * This field contains the bytes of the ChaincodeProposalPayload message from
     * the original invocation (essentially the arguments) after the application
     * of the visibility function. The main visibility modes are "full" (the
     * entire ChaincodeProposalPayload message is included here), "hash" (only
     * the hash of the ChaincodeProposalPayload message is included) or
     * "nothing".  This field will be used to check the consistency of
     * ProposalResponsePayload.proposalHash.  For the CHAINCODE type,
     * ProposalResponsePayload.proposalHash is supposed to be H(ProposalHeader ||
     * f(ChaincodeProposalPayload)) where f is the visibility function.
     * </pre>
     *
     * <code>bytes chaincode_proposal_payload = 1;</code>
     */
    private $chaincode_proposal_payload = '';
    /**
     * <pre>
     * The list of actions to apply to the ledger
     * </pre>
     *
     * <code>.protos.ChaincodeEndorsedAction action = 2;</code>
     */
    private $action = null;

    public function __construct() {
        \GPBMetadata\Peer\Transaction::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * This field contains the bytes of the ChaincodeProposalPayload message from
     * the original invocation (essentially the arguments) after the application
     * of the visibility function. The main visibility modes are "full" (the
     * entire ChaincodeProposalPayload message is included here), "hash" (only
     * the hash of the ChaincodeProposalPayload message is included) or
     * "nothing".  This field will be used to check the consistency of
     * ProposalResponsePayload.proposalHash.  For the CHAINCODE type,
     * ProposalResponsePayload.proposalHash is supposed to be H(ProposalHeader ||
     * f(ChaincodeProposalPayload)) where f is the visibility function.
     * </pre>
     *
     * <code>bytes chaincode_proposal_payload = 1;</code>
     */
    public function getChaincodeProposalPayload()
    {
        return $this->chaincode_proposal_payload;
    }

    /**
     * <pre>
     * This field contains the bytes of the ChaincodeProposalPayload message from
     * the original invocation (essentially the arguments) after the application
     * of the visibility function. The main visibility modes are "full" (the
     * entire ChaincodeProposalPayload message is included here), "hash" (only
     * the hash of the ChaincodeProposalPayload message is included) or
     * "nothing".  This field will be used to check the consistency of
     * ProposalResponsePayload.proposalHash.  For the CHAINCODE type,
     * ProposalResponsePayload.proposalHash is supposed to be H(ProposalHeader ||
     * f(ChaincodeProposalPayload)) where f is the visibility function.
     * </pre>
     *
     * <code>bytes chaincode_proposal_payload = 1;</code>
     */
    public function setChaincodeProposalPayload($var)
    {
        GPBUtil::checkString($var, False);
        $this->chaincode_proposal_payload = $var;
    }

    /**
     * <pre>
     * The list of actions to apply to the ledger
     * </pre>
     *
     * <code>.protos.ChaincodeEndorsedAction action = 2;</code>
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * <pre>
     * The list of actions to apply to the ledger
     * </pre>
     *
     * <code>.protos.ChaincodeEndorsedAction action = 2;</code>
     */
    public function setAction(&$var)
    {
        GPBUtil::checkMessage($var, \Protos\ChaincodeEndorsedAction::class);
        $this->action = $var;
    }

}

