<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/chaincode.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 *ChaincodeID contains the path as specified by the deploy transaction
 *that created it as well as the hashCode that is generated by the
 *system for the path. From the user level (ie, CLI, REST API and so on)
 *deploy transaction is expected to provide the path and other requests
 *are expected to provide the hashCode. The other value will be ignored.
 *Internally, the structure could contain both values. For instance, the
 *hashCode will be set when first generated using the path
 * </pre>
 *
 * Protobuf type <code>protos.ChaincodeID</code>
 */
class ChaincodeID extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *deploy transaction will use the path
     * </pre>
     *
     * <code>string path = 1;</code>
     */
    private $path = '';
    /**
     * <pre>
     *all other requests will use the name (really a hashcode) generated by
     *the deploy transaction
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * <pre>
     *user friendly version name for the chaincode
     * </pre>
     *
     * <code>string version = 3;</code>
     */
    private $version = '';

    public function __construct() {
        \GPBMetadata\Peer\Chaincode::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     *deploy transaction will use the path
     * </pre>
     *
     * <code>string path = 1;</code>
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * <pre>
     *deploy transaction will use the path
     * </pre>
     *
     * <code>string path = 1;</code>
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;
    }

    /**
     * <pre>
     *all other requests will use the name (really a hashcode) generated by
     *the deploy transaction
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <pre>
     *all other requests will use the name (really a hashcode) generated by
     *the deploy transaction
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <pre>
     *user friendly version name for the chaincode
     * </pre>
     *
     * <code>string version = 3;</code>
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * <pre>
     *user friendly version name for the chaincode
     * </pre>
     *
     * <code>string version = 3;</code>
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;
    }

}

