<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/chaincode.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Carries the chaincode function and its arguments.
 * </pre>
 *
 * Protobuf type <code>protos.ChaincodeInvocationSpec</code>
 */
class ChaincodeInvocationSpec extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.protos.ChaincodeSpec chaincode_spec = 1;</code>
     */
    private $chaincode_spec = null;
    /**
     * <pre>
     * This field can contain a user-specified ID generation algorithm
     * If supplied, this will be used to generate a ID
     * If not supplied (left empty), sha256base64 will be used
     * The algorithm consists of two parts:
     *  1, a hash function
     *  2, a decoding used to decode user (string) input to bytes
     * Currently, SHA256 with BASE64 is supported (e.g. idGenerationAlg='sha256base64')
     * </pre>
     *
     * <code>string id_generation_alg = 2;</code>
     */
    private $id_generation_alg = '';

    public function __construct() {
        \GPBMetadata\Peer\Chaincode::initOnce();
        parent::__construct();
    }

    /**
     * <code>.protos.ChaincodeSpec chaincode_spec = 1;</code>
     */
    public function getChaincodeSpec()
    {
        return $this->chaincode_spec;
    }

    /**
     * <code>.protos.ChaincodeSpec chaincode_spec = 1;</code>
     */
    public function setChaincodeSpec(&$var)
    {
        GPBUtil::checkMessage($var, \Protos\ChaincodeSpec::class);
        $this->chaincode_spec = $var;
    }

    /**
     * <pre>
     * This field can contain a user-specified ID generation algorithm
     * If supplied, this will be used to generate a ID
     * If not supplied (left empty), sha256base64 will be used
     * The algorithm consists of two parts:
     *  1, a hash function
     *  2, a decoding used to decode user (string) input to bytes
     * Currently, SHA256 with BASE64 is supported (e.g. idGenerationAlg='sha256base64')
     * </pre>
     *
     * <code>string id_generation_alg = 2;</code>
     */
    public function getIdGenerationAlg()
    {
        return $this->id_generation_alg;
    }

    /**
     * <pre>
     * This field can contain a user-specified ID generation algorithm
     * If supplied, this will be used to generate a ID
     * If not supplied (left empty), sha256base64 will be used
     * The algorithm consists of two parts:
     *  1, a hash function
     *  2, a decoding used to decode user (string) input to bytes
     * Currently, SHA256 with BASE64 is supported (e.g. idGenerationAlg='sha256base64')
     * </pre>
     *
     * <code>string id_generation_alg = 2;</code>
     */
    public function setIdGenerationAlg($var)
    {
        GPBUtil::checkString($var, True);
        $this->id_generation_alg = $var;
    }

}

