<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/query.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * ChaincodeQueryResponse returns information about each chaincode that pertains
 * to a query in lscc.go, such as GetChaincodes (returns all chaincodes
 * instantiated on a channel), and GetInstalledChaincodes (returns all chaincodes
 * installed on a peer)
 * </pre>
 *
 * Protobuf type <code>protos.ChaincodeQueryResponse</code>
 */
class ChaincodeQueryResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .protos.ChaincodeInfo chaincodes = 1;</code>
     */
    private $chaincodes;

    public function __construct() {
        \GPBMetadata\Peer\Query::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .protos.ChaincodeInfo chaincodes = 1;</code>
     */
    public function getChaincodes()
    {
        return $this->chaincodes;
    }

    /**
     * <code>repeated .protos.ChaincodeInfo chaincodes = 1;</code>
     */
    public function setChaincodes(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\ChaincodeInfo::class);
        $this->chaincodes = $arr;
    }

}

