<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/query.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * ChannelInfo contains general information about channels
 * </pre>
 *
 * Protobuf type <code>protos.ChannelInfo</code>
 */
class ChannelInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string channel_id = 1;</code>
     */
    private $channel_id = '';

    public function __construct() {
        \GPBMetadata\Peer\Query::initOnce();
        parent::__construct();
    }

    /**
     * <code>string channel_id = 1;</code>
     */
    public function getChannelId()
    {
        return $this->channel_id;
    }

    /**
     * <code>string channel_id = 1;</code>
     */
    public function setChannelId($var)
    {
        GPBUtil::checkString($var, True);
        $this->channel_id = $var;
    }

}

