<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/proposal_response.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * An endorsement is a signature of an endorser over a proposal response.  By
 * producing an endorsement message, an endorser implicitly "approves" that
 * proposal response and the actions contained therein. When enough
 * endorsements have been collected, a transaction can be generated out of a
 * set of proposal responses.  Note that this message only contains an identity
 * and a signature but no signed payload. This is intentional because
 * endorsements are supposed to be collected in a transaction, and they are all
 * expected to endorse a single proposal response/action (many endorsements
 * over a single proposal response)
 * </pre>
 *
 * Protobuf type <code>protos.Endorsement</code>
 */
class Endorsement extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Identity of the endorser (e.g. its certificate)
     * </pre>
     *
     * <code>bytes endorser = 1;</code>
     */
    private $endorser = '';
    /**
     * <pre>
     * Signature of the payload included in ProposalResponse concatenated with
     * the endorser's certificate; ie, sign(ProposalResponse.payload + endorser)
     * </pre>
     *
     * <code>bytes signature = 2;</code>
     */
    private $signature = '';

    public function __construct() {
        \GPBMetadata\Peer\ProposalResponse::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Identity of the endorser (e.g. its certificate)
     * </pre>
     *
     * <code>bytes endorser = 1;</code>
     */
    public function getEndorser()
    {
        return $this->endorser;
    }

    /**
     * <pre>
     * Identity of the endorser (e.g. its certificate)
     * </pre>
     *
     * <code>bytes endorser = 1;</code>
     */
    public function setEndorser($var)
    {
        GPBUtil::checkString($var, False);
        $this->endorser = $var;
    }

    /**
     * <pre>
     * Signature of the payload included in ProposalResponse concatenated with
     * the endorser's certificate; ie, sign(ProposalResponse.payload + endorser)
     * </pre>
     *
     * <code>bytes signature = 2;</code>
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * <pre>
     * Signature of the payload included in ProposalResponse concatenated with
     * the endorser's certificate; ie, sign(ProposalResponse.payload + endorser)
     * </pre>
     *
     * <code>bytes signature = 2;</code>
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->signature = $var;
    }

}

