<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/events.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>protos.Interest</code>
 */
class Interest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.protos.EventType event_type = 1;</code>
     */
    private $event_type = 0;
    /**
     * <code>string chainID = 3;</code>
     */
    private $chainID = '';
    protected $RegInfo;

    public function __construct() {
        \GPBMetadata\Peer\Events::initOnce();
        parent::__construct();
    }

    /**
     * <code>.protos.EventType event_type = 1;</code>
     */
    public function getEventType()
    {
        return $this->event_type;
    }

    /**
     * <code>.protos.EventType event_type = 1;</code>
     */
    public function setEventType($var)
    {
        GPBUtil::checkEnum($var, \Protos\EventType::class);
        $this->event_type = $var;
    }

    /**
     * <code>.protos.ChaincodeReg chaincode_reg_info = 2;</code>
     */
    public function getChaincodeRegInfo()
    {
        return $this->readOneof(2);
    }

    /**
     * <code>.protos.ChaincodeReg chaincode_reg_info = 2;</code>
     */
    public function setChaincodeRegInfo(&$var)
    {
        GPBUtil::checkMessage($var, \Protos\ChaincodeReg::class);
        $this->writeOneof(2, $var);
    }

    /**
     * <code>string chainID = 3;</code>
     */
    public function getChainID()
    {
        return $this->chainID;
    }

    /**
     * <code>string chainID = 3;</code>
     */
    public function setChainID($var)
    {
        GPBUtil::checkString($var, True);
        $this->chainID = $var;
    }

    public function getRegInfo()
    {
        return $this->whichOneof("RegInfo");
    }

}

