<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/proposal.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * A Proposal is sent to an endorser for endorsement.  The proposal contains:
 * 1. A header which should be unmarshaled to a Header message.  Note that
 *    Header is both the header of a Proposal and of a Transaction, in that i)
 *    both headers should be unmarshaled to this message; and ii) it is used to
 *    compute cryptographic hashes and signatures.  The header has fields common
 *    to all proposals/transactions.  In addition it has a type field for
 *    additional customization. An example of this is the ChaincodeHeaderExtension
 *    message used to extend the Header for type CHAINCODE.
 * 2. A payload whose type depends on the header's type field.
 * 3. An extension whose type depends on the header's type field.
 * Let us see an example. For type CHAINCODE (see the Header message),
 * we have the following:
 * 1. The header is a Header message whose extensions field is a
 *    ChaincodeHeaderExtension message.
 * 2. The payload is a ChaincodeProposalPayload message.
 * 3. The extension is a ChaincodeAction that might be used to ask the
 *    endorsers to endorse a specific ChaincodeAction, thus emulating the
 *    submitting peer model.
 * </pre>
 *
 * Protobuf type <code>protos.Proposal</code>
 */
class Proposal extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The header of the proposal. It is the bytes of the Header
     * </pre>
     *
     * <code>bytes header = 1;</code>
     */
    private $header = '';
    /**
     * <pre>
     * The payload of the proposal as defined by the type in the proposal
     * header.
     * </pre>
     *
     * <code>bytes payload = 2;</code>
     */
    private $payload = '';
    /**
     * <pre>
     * Optional extensions to the proposal. Its content depends on the Header's
     * type field.  For the type CHAINCODE, it might be the bytes of a
     * ChaincodeAction message.
     * </pre>
     *
     * <code>bytes extension = 3;</code>
     */
    private $extension = '';

    public function __construct() {
        \GPBMetadata\Peer\Proposal::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The header of the proposal. It is the bytes of the Header
     * </pre>
     *
     * <code>bytes header = 1;</code>
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * <pre>
     * The header of the proposal. It is the bytes of the Header
     * </pre>
     *
     * <code>bytes header = 1;</code>
     */
    public function setHeader($var)
    {
        GPBUtil::checkString($var, False);
        $this->header = $var;
    }

    /**
     * <pre>
     * The payload of the proposal as defined by the type in the proposal
     * header.
     * </pre>
     *
     * <code>bytes payload = 2;</code>
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * <pre>
     * The payload of the proposal as defined by the type in the proposal
     * header.
     * </pre>
     *
     * <code>bytes payload = 2;</code>
     */
    public function setPayload($var)
    {
        GPBUtil::checkString($var, False);
        $this->payload = $var;
    }

    /**
     * <pre>
     * Optional extensions to the proposal. Its content depends on the Header's
     * type field.  For the type CHAINCODE, it might be the bytes of a
     * ChaincodeAction message.
     * </pre>
     *
     * <code>bytes extension = 3;</code>
     */
    public function getExtension()
    {
        return $this->extension;
    }

    /**
     * <pre>
     * Optional extensions to the proposal. Its content depends on the Header's
     * type field.  For the type CHAINCODE, it might be the bytes of a
     * ChaincodeAction message.
     * </pre>
     *
     * <code>bytes extension = 3;</code>
     */
    public function setExtension($var)
    {
        GPBUtil::checkString($var, False);
        $this->extension = $var;
    }

}

