<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/events.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 *Rejection is sent by consumers for erroneous transaction rejection events
 *string type - "rejection"
 * </pre>
 *
 * Protobuf type <code>protos.Rejection</code>
 */
class Rejection extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.protos.Transaction tx = 1;</code>
     */
    private $tx = null;
    /**
     * <code>string error_msg = 2;</code>
     */
    private $error_msg = '';

    public function __construct() {
        \GPBMetadata\Peer\Events::initOnce();
        parent::__construct();
    }

    /**
     * <code>.protos.Transaction tx = 1;</code>
     */
    public function getTx()
    {
        return $this->tx;
    }

    /**
     * <code>.protos.Transaction tx = 1;</code>
     */
    public function setTx(&$var)
    {
        GPBUtil::checkMessage($var, \Protos\Transaction::class);
        $this->tx = $var;
    }

    /**
     * <code>string error_msg = 2;</code>
     */
    public function getErrorMsg()
    {
        return $this->error_msg;
    }

    /**
     * <code>string error_msg = 2;</code>
     */
    public function setErrorMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->error_msg = $var;
    }

}

