<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orderer/configuration.proto

namespace GPBMetadata\Orderer;

class Configuration
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af1020a1b6f7264657265722f636f6e66696775726174696f6e2e70726f" .
            "746f12076f726465726572221d0a0d436f6e73656e73757354797065120c" .
            "0a0474797065180120012809225f0a09426174636853697a6512190a116d" .
            "61785f6d6573736167655f636f756e7418012001280d121a0a126162736f" .
            "6c7574655f6d61785f627974657318022001280d121b0a13707265666572" .
            "7265645f6d61785f627974657318032001280d221f0a0c42617463685469" .
            "6d656f7574120f0a0774696d656f7574180120012809221f0a0c4b61666b" .
            "6142726f6b657273120f0a0762726f6b65727318012003280922280a1343" .
            "68616e6e656c5265737472696374696f6e7312110a096d61785f636f756e" .
            "7418012001280442550a256f72672e68797065726c65646765722e666162" .
            "7269632e70726f746f732e6f7264657265725a2c6769746875622e636f6d" .
            "2f68797065726c65646765722f6661627269632f70726f746f732f6f7264" .
            "65726572620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

