<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/configuration.proto

namespace Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * BlockDataHashingStructure is encoded into the configuration transaction as a configuration item of
 * type Chain with a Key of "BlockDataHashingStructure" and a Value of HashingAlgorithm as marshaled protobuf bytes
 * </pre>
 *
 * Protobuf type <code>common.BlockDataHashingStructure</code>
 */
class BlockDataHashingStructure extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * width specifies the width of the Merkle tree to use when computing the BlockDataHash
     * in order to replicate flat hashing, set this width to MAX_UINT32
     * </pre>
     *
     * <code>uint32 width = 1;</code>
     */
    private $width = 0;

    public function __construct() {
        \GPBMetadata\Common\Configuration::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * width specifies the width of the Merkle tree to use when computing the BlockDataHash
     * in order to replicate flat hashing, set this width to MAX_UINT32
     * </pre>
     *
     * <code>uint32 width = 1;</code>
     */
    public function getWidth()
    {
        return $this->width;
    }

    /**
     * <pre>
     * width specifies the width of the Merkle tree to use when computing the BlockDataHash
     * in order to replicate flat hashing, set this width to MAX_UINT32
     * </pre>
     *
     * <code>uint32 width = 1;</code>
     */
    public function setWidth($var)
    {
        GPBUtil::checkUint32($var);
        $this->width = $var;
    }

}

