<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/common.proto

namespace Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Header is a generic replay prevention and identity message to include in a signed payload
 * </pre>
 *
 * Protobuf type <code>common.ChannelHeader</code>
 */
class ChannelHeader extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Header types 0-10000 are reserved and defined by HeaderType
     * </pre>
     *
     * <code>int32 type = 1;</code>
     */
    private $type = 0;
    /**
     * <pre>
     * Version indicates message protocol version
     * </pre>
     *
     * <code>int32 version = 2;</code>
     */
    private $version = 0;
    /**
     * <pre>
     * Timestamp is the local time when the message was created
     * by the sender
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    private $timestamp = null;
    /**
     * <pre>
     * Identifier of the channel this message is bound for
     * </pre>
     *
     * <code>string channel_id = 4;</code>
     */
    private $channel_id = '';
    /**
     * <pre>
     * An unique identifier that is used end-to-end.
     *  -  set by higher layers such as end user or SDK
     *  -  passed to the endorser (which will check for uniqueness)
     *  -  as the header is passed along unchanged, it will be
     *     be retrieved by the committer (uniqueness check here as well)
     *  -  to be stored in the ledger
     * </pre>
     *
     * <code>string tx_id = 5;</code>
     */
    private $tx_id = '';
    /**
     * <pre>
     * The epoch in which this header was generated, where epoch is defined based on block height
     * Epoch in which the response has been generated. This field identifies a
     * logical window of time. A proposal response is accepted by a peer only if
     * two conditions hold:
     * 1. the epoch specified in the message is the current epoch
     * 2. this message has been only seen once during this epoch (i.e. it hasn't
     *    been replayed)
     * </pre>
     *
     * <code>uint64 epoch = 6;</code>
     */
    private $epoch = 0;
    /**
     * <pre>
     * Extension that may be attached based on the header type
     * </pre>
     *
     * <code>bytes extension = 7;</code>
     */
    private $extension = '';

    public function __construct() {
        \GPBMetadata\Common\Common::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Header types 0-10000 are reserved and defined by HeaderType
     * </pre>
     *
     * <code>int32 type = 1;</code>
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * <pre>
     * Header types 0-10000 are reserved and defined by HeaderType
     * </pre>
     *
     * <code>int32 type = 1;</code>
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->type = $var;
    }

    /**
     * <pre>
     * Version indicates message protocol version
     * </pre>
     *
     * <code>int32 version = 2;</code>
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * <pre>
     * Version indicates message protocol version
     * </pre>
     *
     * <code>int32 version = 2;</code>
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->version = $var;
    }

    /**
     * <pre>
     * Timestamp is the local time when the message was created
     * by the sender
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * <pre>
     * Timestamp is the local time when the message was created
     * by the sender
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    public function setTimestamp(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->timestamp = $var;
    }

    /**
     * <pre>
     * Identifier of the channel this message is bound for
     * </pre>
     *
     * <code>string channel_id = 4;</code>
     */
    public function getChannelId()
    {
        return $this->channel_id;
    }

    /**
     * <pre>
     * Identifier of the channel this message is bound for
     * </pre>
     *
     * <code>string channel_id = 4;</code>
     */
    public function setChannelId($var)
    {
        GPBUtil::checkString($var, True);
        $this->channel_id = $var;
    }

    /**
     * <pre>
     * An unique identifier that is used end-to-end.
     *  -  set by higher layers such as end user or SDK
     *  -  passed to the endorser (which will check for uniqueness)
     *  -  as the header is passed along unchanged, it will be
     *     be retrieved by the committer (uniqueness check here as well)
     *  -  to be stored in the ledger
     * </pre>
     *
     * <code>string tx_id = 5;</code>
     */
    public function getTxId()
    {
        return $this->tx_id;
    }

    /**
     * <pre>
     * An unique identifier that is used end-to-end.
     *  -  set by higher layers such as end user or SDK
     *  -  passed to the endorser (which will check for uniqueness)
     *  -  as the header is passed along unchanged, it will be
     *     be retrieved by the committer (uniqueness check here as well)
     *  -  to be stored in the ledger
     * </pre>
     *
     * <code>string tx_id = 5;</code>
     */
    public function setTxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->tx_id = $var;
    }

    /**
     * <pre>
     * The epoch in which this header was generated, where epoch is defined based on block height
     * Epoch in which the response has been generated. This field identifies a
     * logical window of time. A proposal response is accepted by a peer only if
     * two conditions hold:
     * 1. the epoch specified in the message is the current epoch
     * 2. this message has been only seen once during this epoch (i.e. it hasn't
     *    been replayed)
     * </pre>
     *
     * <code>uint64 epoch = 6;</code>
     */
    public function getEpoch()
    {
        return $this->epoch;
    }

    /**
     * <pre>
     * The epoch in which this header was generated, where epoch is defined based on block height
     * Epoch in which the response has been generated. This field identifies a
     * logical window of time. A proposal response is accepted by a peer only if
     * two conditions hold:
     * 1. the epoch specified in the message is the current epoch
     * 2. this message has been only seen once during this epoch (i.e. it hasn't
     *    been replayed)
     * </pre>
     *
     * <code>uint64 epoch = 6;</code>
     */
    public function setEpoch($var)
    {
        GPBUtil::checkUint64($var);
        $this->epoch = $var;
    }

    /**
     * <pre>
     * Extension that may be attached based on the header type
     * </pre>
     *
     * <code>bytes extension = 7;</code>
     */
    public function getExtension()
    {
        return $this->extension;
    }

    /**
     * <pre>
     * Extension that may be attached based on the header type
     * </pre>
     *
     * <code>bytes extension = 7;</code>
     */
    public function setExtension($var)
    {
        GPBUtil::checkString($var, False);
        $this->extension = $var;
    }

}

