<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/configtx.proto

namespace Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Configs represents the config for a particular channel
 * </pre>
 *
 * Protobuf type <code>common.Configs</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>uint64 sequence = 1;</code>
     */
    private $sequence = 0;
    /**
     * <code>.common.ConfigGroup channel_group = 2;</code>
     */
    private $channel_group = null;

    public function __construct() {
        \GPBMetadata\Common\Configtx::initOnce();
        parent::__construct();
    }

    /**
     * <code>uint64 sequence = 1;</code>
     */
    public function getSequence()
    {
        return $this->sequence;
    }

    /**
     * <code>uint64 sequence = 1;</code>
     */
    public function setSequence($var)
    {
        GPBUtil::checkUint64($var);
        $this->sequence = $var;
    }

    /**
     * <code>.common.ConfigGroup channel_group = 2;</code>
     */
    public function getChannelGroup()
    {
        return $this->channel_group;
    }

    /**
     * <code>.common.ConfigGroup channel_group = 2;</code>
     */
    public function setChannelGroup(&$var)
    {
        GPBUtil::checkMessage($var, \Common\ConfigGroup::class);
        $this->channel_group = $var;
    }

}

