<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/configtx.proto

namespace Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>common.ConfigPolicy</code>
 */
class ConfigPolicy extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>uint64 version = 1;</code>
     */
    private $version = 0;
    /**
     * <code>.common.Policy policy = 2;</code>
     */
    private $policy = null;
    /**
     * <code>string mod_policy = 3;</code>
     */
    private $mod_policy = '';

    public function __construct() {
        \GPBMetadata\Common\Configtx::initOnce();
        parent::__construct();
    }

    /**
     * <code>uint64 version = 1;</code>
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * <code>uint64 version = 1;</code>
     */
    public function setVersion($var)
    {
        GPBUtil::checkUint64($var);
        $this->version = $var;
    }

    /**
     * <code>.common.Policy policy = 2;</code>
     */
    public function getPolicy()
    {
        return $this->policy;
    }

    /**
     * <code>.common.Policy policy = 2;</code>
     */
    public function setPolicy(&$var)
    {
        GPBUtil::checkMessage($var, \Common\Policy::class);
        $this->policy = $var;
    }

    /**
     * <code>string mod_policy = 3;</code>
     */
    public function getModPolicy()
    {
        return $this->mod_policy;
    }

    /**
     * <code>string mod_policy = 3;</code>
     */
    public function setModPolicy($var)
    {
        GPBUtil::checkString($var, True);
        $this->mod_policy = $var;
    }

}

