<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/configtx.proto

namespace Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * ConfigEnvelope is designed to contain _all_ configuration for a chain with no dependency
 * on previous configuration transactions.
 * It is generated with the following scheme:
 *   1. Retrieve the existing configuration
 *   2. Note the config properties (ConfigValue, ConfigPolicy, ConfigGroup) to be modified
 *   3. Add any intermediate ConfigGroups to the ConfigUpdate.read_set (sparsely)
 *   4. Add any additional desired dependencies to ConfigUpdate.read_set (sparsely)
 *   5. Modify the config properties, incrementing each version by 1, set them in the ConfigUpdate.write_set
 *      Note: any element not modified but specified should already be in the read_set, so may be specified sparsely
 *   6. Create ConfigUpdate message and marshal it into ConfigUpdateEnvelope.update and encode the required signatures
 *     a) Each signature is of type ConfigSignature
 *     b) The ConfigSignature signature is over the concatenation of signature_header and the ConfigUpdate bytes (which includes a ChainHeader)
 *   5. Submit new Configs for ordering in Envelope signed by submitter
 *     a) The Envelope Payload has data set to the marshaled ConfigEnvelope
 *     b) The Envelope Payload has a header of type Header.Type.CONFIG_UPDATE
 * The configuration manager will verify:
 *   1. All items in the read_set exist at the read versions
 *   2. All items in the write_set at a different version than, or not in, the read_set have been appropriately signed according to their mod_policy
 *   3. The new configuration satisfies the ConfigSchema
 * </pre>
 *
 * Protobuf type <code>common.ConfigEnvelope</code>
 */
class ConfigEnvelope extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * A marshaled Configs structure
     * </pre>
     *
     * <code>.common.Configs config = 1;</code>
     */
    private $config = null;
    /**
     * <pre>
     * The last CONFIG_UPDATE message which generated this current configuration
     * </pre>
     *
     * <code>.common.Envelope last_update = 2;</code>
     */
    private $last_update = null;

    public function __construct() {
        \GPBMetadata\Common\Configtx::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * A marshaled Configs structure
     * </pre>
     *
     * <code>.common.Configs config = 1;</code>
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * <pre>
     * A marshaled Configs structure
     * </pre>
     *
     * <code>.common.Configs config = 1;</code>
     */
    public function setConfig(&$var)
    {
        GPBUtil::checkMessage($var, \Common\Config::class);
        $this->config = $var;
    }

    /**
     * <pre>
     * The last CONFIG_UPDATE message which generated this current configuration
     * </pre>
     *
     * <code>.common.Envelope last_update = 2;</code>
     */
    public function getLastUpdate()
    {
        return $this->last_update;
    }

    /**
     * <pre>
     * The last CONFIG_UPDATE message which generated this current configuration
     * </pre>
     *
     * <code>.common.Envelope last_update = 2;</code>
     */
    public function setLastUpdate(&$var)
    {
        GPBUtil::checkMessage($var, \Common\Envelope::class);
        $this->last_update = $var;
    }

}

