<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/configtx.proto

namespace Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * ConfigGroup is the hierarchical data structure for holding config
 * </pre>
 *
 * Protobuf type <code>common.ConfigGroup</code>
 */
class ConfigGroup extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>uint64 version = 1;</code>
     */
    private $version = 0;
    /**
     * <code>map&lt;string, .common.ConfigGroup&gt; groups = 2;</code>
     */
    private $groups;
    /**
     * <code>map&lt;string, .common.ConfigValue&gt; values = 3;</code>
     */
    private $values;
    /**
     * <code>map&lt;string, .common.ConfigPolicy&gt; policies = 4;</code>
     */
    private $policies;
    /**
     * <code>string mod_policy = 5;</code>
     */
    private $mod_policy = '';

    public function __construct() {
        \GPBMetadata\Common\Configtx::initOnce();
        parent::__construct();
    }

    /**
     * <code>uint64 version = 1;</code>
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * <code>uint64 version = 1;</code>
     */
    public function setVersion($var)
    {
        GPBUtil::checkUint64($var);
        $this->version = $var;
    }

    /**
     * <code>map&lt;string, .common.ConfigGroup&gt; groups = 2;</code>
     */
    public function getGroups()
    {
        return $this->groups;
    }

    /**
     * <code>map&lt;string, .common.ConfigGroup&gt; groups = 2;</code>
     */
    public function setGroups(&$var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Common\ConfigGroup::class);
        $this->groups = $arr;
    }

    /**
     * <code>map&lt;string, .common.ConfigValue&gt; values = 3;</code>
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * <code>map&lt;string, .common.ConfigValue&gt; values = 3;</code>
     */
    public function setValues(&$var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Common\ConfigValue::class);
        $this->values = $arr;
    }

    /**
     * <code>map&lt;string, .common.ConfigPolicy&gt; policies = 4;</code>
     */
    public function getPolicies()
    {
        return $this->policies;
    }

    /**
     * <code>map&lt;string, .common.ConfigPolicy&gt; policies = 4;</code>
     */
    public function setPolicies(&$var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Common\ConfigPolicy::class);
        $this->policies = $arr;
    }

    /**
     * <code>string mod_policy = 5;</code>
     */
    public function getModPolicy()
    {
        return $this->mod_policy;
    }

    /**
     * <code>string mod_policy = 5;</code>
     */
    public function setModPolicy($var)
    {
        GPBUtil::checkString($var, True);
        $this->mod_policy = $var;
    }

}

