<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/policies.proto

namespace Common;

/**
 * Protobuf enum <code>common.ImplicitMetaPolicy.Rule</code>
 */
class ImplicitMetaPolicy_Rule
{
    /**
     * <pre>
     * Requires any of the sub-policies be satisfied, if no sub-policies exist, always returns true
     * </pre>
     *
     * <code>ANY = 0;</code>
     */
    const ANY = 0;
    /**
     * <pre>
     * Requires all of the sub-policies be satisfied
     * </pre>
     *
     * <code>ALL = 1;</code>
     */
    const ALL = 1;
    /**
     * <pre>
     * Requires a strict majority (greater than half) of the sub-policies be satisfied
     * </pre>
     *
     * <code>MAJORITY = 2;</code>
     */
    const MAJORITY = 2;
}

