<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msp/msp_principal.proto

namespace Common;

/**
 * Protobuf enum <code>common.MSPPrincipal.Classification</code>
 */
class MSPPrincipal_Classification
{
    /**
     * <pre>
     * Represents the one of the dedicated MSP roles, the
     * </pre>
     *
     * <code>ROLE = 0;</code>
     */
    const ROLE = 0;
    /**
     * <pre>
     * one of a member of MSP network, and the one of an
     * administrator of an MSP network
     * </pre>
     *
     * <code>ORGANIZATION_UNIT = 1;</code>
     */
    const ORGANIZATION_UNIT = 1;
    /**
     * <pre>
     * groupping of entities, per MSP affiliation
     * E.g., this can well be represented by an MSP's
     * Organization unit
     * </pre>
     *
     * <code>IDENTITY = 2;</code>
     */
    const IDENTITY = 2;
}

