<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/common.proto

namespace Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Payload is the message contents (and header to allow for signing)
 * </pre>
 *
 * Protobuf type <code>common.Payload</code>
 */
class Payload extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Header is included to provide identity and prevent replay
     * </pre>
     *
     * <code>.common.Header header = 1;</code>
     */
    private $header = null;
    /**
     * <pre>
     * Data, the encoding of which is defined by the type in the header
     * </pre>
     *
     * <code>bytes data = 2;</code>
     */
    private $data = '';

    public function __construct() {
        \GPBMetadata\Common\Common::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Header is included to provide identity and prevent replay
     * </pre>
     *
     * <code>.common.Header header = 1;</code>
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * <pre>
     * Header is included to provide identity and prevent replay
     * </pre>
     *
     * <code>.common.Header header = 1;</code>
     */
    public function setHeader(&$var)
    {
        GPBUtil::checkMessage($var, \Common\Header::class);
        $this->header = $var;
    }

    /**
     * <pre>
     * Data, the encoding of which is defined by the type in the header
     * </pre>
     *
     * <code>bytes data = 2;</code>
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * <pre>
     * Data, the encoding of which is defined by the type in the header
     * </pre>
     *
     * <code>bytes data = 2;</code>
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;
    }

}

