<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/proposal.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * ChaincodeProposalPayload is the Proposal's payload message to be used when
 * the Header's type is CHAINCODE.  It contains the arguments for this
 * invocation.
 * </pre>
 *
 * Protobuf type <code>protos.ChaincodeProposalPayload</code>
 */
class ChaincodeProposalPayload extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Input contains the arguments for this invocation. If this invocation
     * deploys a new chaincode, ESCC/VSCC are part of this field.
     * </pre>
     *
     * <code>bytes input = 1;</code>
     */
    private $input = '';
    /**
     * <pre>
     * TransientMap contains data (e.g. cryptographic material) that might be used
     * to implement some form of application-level confidentiality. The contents
     * of this field are supposed to always be omitted from the transaction and
     * excluded from the ledger.
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; TransientMap = 2;</code>
     */
    private $TransientMap;

    public function __construct() {
        \GPBMetadata\Peer\Proposal::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Input contains the arguments for this invocation. If this invocation
     * deploys a new chaincode, ESCC/VSCC are part of this field.
     * </pre>
     *
     * <code>bytes input = 1;</code>
     */
    public function getInput()
    {
        return $this->input;
    }

    /**
     * <pre>
     * Input contains the arguments for this invocation. If this invocation
     * deploys a new chaincode, ESCC/VSCC are part of this field.
     * </pre>
     *
     * <code>bytes input = 1;</code>
     */
    public function setInput($var)
    {
        GPBUtil::checkString($var, False);
        $this->input = $var;
    }

    /**
     * <pre>
     * TransientMap contains data (e.g. cryptographic material) that might be used
     * to implement some form of application-level confidentiality. The contents
     * of this field are supposed to always be omitted from the transaction and
     * excluded from the ledger.
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; TransientMap = 2;</code>
     */
    public function getTransientMap()
    {
        return $this->TransientMap;
    }

    /**
     * <pre>
     * TransientMap contains data (e.g. cryptographic material) that might be used
     * to implement some form of application-level confidentiality. The contents
     * of this field are supposed to always be omitted from the transaction and
     * excluded from the ledger.
     * </pre>
     *
     * <code>map&lt;string, bytes&gt; TransientMap = 2;</code>
     */
    public function setTransientMap(&$var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->TransientMap = $arr;
    }

}

