<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/chaincode.proto

namespace Protos;

/**
 * Protobuf enum <code>protos.ChaincodeDeploymentSpec.ExecutionEnvironment</code>
 */
class ChaincodeDeploymentSpec_ExecutionEnvironment
{
    /**
     * <code>DOCKER = 0;</code>
     */
    const DOCKER = 0;
    /**
     * <code>SYSTEM = 1;</code>
     */
    const SYSTEM = 1;
}

