<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/chaincode.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Specify the deployment of a chaincode.
 * TODO: Define `codePackage`.
 * </pre>
 *
 * Protobuf type <code>protos.ChaincodeDeploymentSpec</code>
 */
class ChaincodeDeploymentSpec extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.protos.ChaincodeSpec chaincode_spec = 1;</code>
     */
    private $chaincode_spec = null;
    /**
     * <pre>
     * Controls when the chaincode becomes executable.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp effective_date = 2;</code>
     */
    private $effective_date = null;
    /**
     * <code>bytes code_package = 3;</code>
     */
    private $code_package = '';
    /**
     * <code>.protos.ChaincodeDeploymentSpec.ExecutionEnvironment exec_env = 4;</code>
     */
    private $exec_env = 0;

    public function __construct() {
        \GPBMetadata\Peer\Chaincode::initOnce();
        parent::__construct();
    }

    /**
     * <code>.protos.ChaincodeSpec chaincode_spec = 1;</code>
     */
    public function getChaincodeSpec()
    {
        return $this->chaincode_spec;
    }

    /**
     * <code>.protos.ChaincodeSpec chaincode_spec = 1;</code>
     */
    public function setChaincodeSpec(&$var)
    {
        GPBUtil::checkMessage($var, \Protos\ChaincodeSpec::class);
        $this->chaincode_spec = $var;
    }

    /**
     * <pre>
     * Controls when the chaincode becomes executable.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp effective_date = 2;</code>
     */
    public function getEffectiveDate()
    {
        return $this->effective_date;
    }

    /**
     * <pre>
     * Controls when the chaincode becomes executable.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp effective_date = 2;</code>
     */
    public function setEffectiveDate(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->effective_date = $var;
    }

    /**
     * <code>bytes code_package = 3;</code>
     */
    public function getCodePackage()
    {
        return $this->code_package;
    }

    /**
     * <code>bytes code_package = 3;</code>
     */
    public function setCodePackage($var)
    {
        GPBUtil::checkString($var, False);
        $this->code_package = $var;
    }

    /**
     * <code>.protos.ChaincodeDeploymentSpec.ExecutionEnvironment exec_env = 4;</code>
     */
    public function getExecEnv()
    {
        return $this->exec_env;
    }

    /**
     * <code>.protos.ChaincodeDeploymentSpec.ExecutionEnvironment exec_env = 4;</code>
     */
    public function setExecEnv($var)
    {
        GPBUtil::checkEnum($var, \Protos\ChaincodeDeploymentSpec_ExecutionEnvironment::class);
        $this->exec_env = $var;
    }

}

