<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/proposal.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * ChaincodeHeaderExtension is the Header's extentions message to be used when
 * the Header's type is CHAINCODE.  This extensions is used to specify which
 * chaincode to invoke and what should appear on the ledger.
 * </pre>
 *
 * Protobuf type <code>protos.ChaincodeHeaderExtension</code>
 */
class ChaincodeHeaderExtension extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The PayloadVisibility field controls to what extent the Proposal's payload
     * (recall that for the type CHAINCODE, it is ChaincodeProposalPayload
     * message) field will be visible in the final transaction and in the ledger.
     * Ideally, it would be configurable, supporting at least 3 main visibility
     * modes:
     * 1. all bytes of the payload are visible;
     * 2. only a hash of the payload is visible;
     * 3. nothing is visible.
     * Notice that the visibility function may be potentially part of the ESCC.
     * In that case it overrides PayloadVisibility field.  Finally notice that
     * this field impacts the content of ProposalResponsePayload.proposalHash.
     * </pre>
     *
     * <code>bytes payload_visibility = 1;</code>
     */
    private $payload_visibility = '';
    /**
     * <pre>
     * The ID of the chaincode to target.
     * </pre>
     *
     * <code>.protos.ChaincodeID chaincode_id = 2;</code>
     */
    private $chaincode_id = null;

    public function __construct() {
        \GPBMetadata\Peer\Proposal::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The PayloadVisibility field controls to what extent the Proposal's payload
     * (recall that for the type CHAINCODE, it is ChaincodeProposalPayload
     * message) field will be visible in the final transaction and in the ledger.
     * Ideally, it would be configurable, supporting at least 3 main visibility
     * modes:
     * 1. all bytes of the payload are visible;
     * 2. only a hash of the payload is visible;
     * 3. nothing is visible.
     * Notice that the visibility function may be potentially part of the ESCC.
     * In that case it overrides PayloadVisibility field.  Finally notice that
     * this field impacts the content of ProposalResponsePayload.proposalHash.
     * </pre>
     *
     * <code>bytes payload_visibility = 1;</code>
     */
    public function getPayloadVisibility()
    {
        return $this->payload_visibility;
    }

    /**
     * <pre>
     * The PayloadVisibility field controls to what extent the Proposal's payload
     * (recall that for the type CHAINCODE, it is ChaincodeProposalPayload
     * message) field will be visible in the final transaction and in the ledger.
     * Ideally, it would be configurable, supporting at least 3 main visibility
     * modes:
     * 1. all bytes of the payload are visible;
     * 2. only a hash of the payload is visible;
     * 3. nothing is visible.
     * Notice that the visibility function may be potentially part of the ESCC.
     * In that case it overrides PayloadVisibility field.  Finally notice that
     * this field impacts the content of ProposalResponsePayload.proposalHash.
     * </pre>
     *
     * <code>bytes payload_visibility = 1;</code>
     */
    public function setPayloadVisibility($var)
    {
        GPBUtil::checkString($var, False);
        $this->payload_visibility = $var;
    }

    /**
     * <pre>
     * The ID of the chaincode to target.
     * </pre>
     *
     * <code>.protos.ChaincodeID chaincode_id = 2;</code>
     */
    public function getChaincodeId()
    {
        return $this->chaincode_id;
    }

    /**
     * <pre>
     * The ID of the chaincode to target.
     * </pre>
     *
     * <code>.protos.ChaincodeID chaincode_id = 2;</code>
     */
    public function setChaincodeId(&$var)
    {
        GPBUtil::checkMessage($var, \Protos\ChaincodeID::class);
        $this->chaincode_id = $var;
    }

}

