<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/events.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 *ChaincodeReg is used for registering chaincode Interests
 *when EventType is CHAINCODE
 * </pre>
 *
 * Protobuf type <code>protos.ChaincodeReg</code>
 */
class ChaincodeReg extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string chaincode_id = 1;</code>
     */
    private $chaincode_id = '';
    /**
     * <code>string event_name = 2;</code>
     */
    private $event_name = '';

    public function __construct() {
        \GPBMetadata\Peer\Events::initOnce();
        parent::__construct();
    }

    /**
     * <code>string chaincode_id = 1;</code>
     */
    public function getChaincodeId()
    {
        return $this->chaincode_id;
    }

    /**
     * <code>string chaincode_id = 1;</code>
     */
    public function setChaincodeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->chaincode_id = $var;
    }

    /**
     * <code>string event_name = 2;</code>
     */
    public function getEventName()
    {
        return $this->event_name;
    }

    /**
     * <code>string event_name = 2;</code>
     */
    public function setEventName($var)
    {
        GPBUtil::checkString($var, True);
        $this->event_name = $var;
    }

}

