<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/query.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * ChannelQueryResponse returns information about each channel that pertains
 * to a query in lscc.go, such as GetChannels (returns all channels for a
 * given peer)
 * </pre>
 *
 * Protobuf type <code>protos.ChannelQueryResponse</code>
 */
class ChannelQueryResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .protos.ChannelInfo channels = 1;</code>
     */
    private $channels;

    public function __construct() {
        \GPBMetadata\Peer\Query::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .protos.ChannelInfo channels = 1;</code>
     */
    public function getChannels()
    {
        return $this->channels;
    }

    /**
     * <code>repeated .protos.ChannelInfo channels = 1;</code>
     */
    public function setChannels(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\ChannelInfo::class);
        $this->channels = $arr;
    }

}

