<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/chaincode.proto

namespace Protos;

/**
 * <pre>
 * Confidentiality Levels
 * </pre>
 *
 * Protobuf enum <code>protos.ConfidentialityLevel</code>
 */
class ConfidentialityLevel
{
    /**
     * <code>PUBLIC = 0;</code>
     */
    const PUBLIC = 0;
    /**
     * <code>CONFIDENTIAL = 1;</code>
     */
    const CONFIDENTIAL = 1;
}

