<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/chaincode_shim.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>protos.GetStateByRange</code>
 */
class GetStateByRange extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string startKey = 1;</code>
     */
    private $startKey = '';
    /**
     * <code>string endKey = 2;</code>
     */
    private $endKey = '';

    public function __construct() {
        \GPBMetadata\Peer\ChaincodeShim::initOnce();
        parent::__construct();
    }

    /**
     * <code>string startKey = 1;</code>
     */
    public function getStartKey()
    {
        return $this->startKey;
    }

    /**
     * <code>string startKey = 1;</code>
     */
    public function setStartKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->startKey = $var;
    }

    /**
     * <code>string endKey = 2;</code>
     */
    public function getEndKey()
    {
        return $this->endKey;
    }

    /**
     * <code>string endKey = 2;</code>
     */
    public function setEndKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->endKey = $var;
    }

}

