<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/admin.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>protos.LogLevelResponse</code>
 */
class LogLevelResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string log_module = 1;</code>
     */
    private $log_module = '';
    /**
     * <code>string log_level = 2;</code>
     */
    private $log_level = '';

    public function __construct() {
        \GPBMetadata\Peer\Admin::initOnce();
        parent::__construct();
    }

    /**
     * <code>string log_module = 1;</code>
     */
    public function getLogModule()
    {
        return $this->log_module;
    }

    /**
     * <code>string log_module = 1;</code>
     */
    public function setLogModule($var)
    {
        GPBUtil::checkString($var, True);
        $this->log_module = $var;
    }

    /**
     * <code>string log_level = 2;</code>
     */
    public function getLogLevel()
    {
        return $this->log_level;
    }

    /**
     * <code>string log_level = 2;</code>
     */
    public function setLogLevel($var)
    {
        GPBUtil::checkString($var, True);
        $this->log_level = $var;
    }

}

