<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/peer.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>protos.PeerEndpoint</code>
 */
class PeerEndpoint extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.protos.PeerID id = 1;</code>
     */
    private $id = null;
    /**
     * <code>string address = 2;</code>
     */
    private $address = '';

    public function __construct() {
        \GPBMetadata\Peer\Peer::initOnce();
        parent::__construct();
    }

    /**
     * <code>.protos.PeerID id = 1;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <code>.protos.PeerID id = 1;</code>
     */
    public function setId(&$var)
    {
        GPBUtil::checkMessage($var, \Protos\PeerID::class);
        $this->id = $var;
    }

    /**
     * <code>string address = 2;</code>
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * <code>string address = 2;</code>
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;
    }

}

