<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/chaincode_shim.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>protos.PutStateInfo</code>
 */
class PutStateInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string key = 1;</code>
     */
    private $key = '';
    /**
     * <code>bytes value = 2;</code>
     */
    private $value = '';

    public function __construct() {
        \GPBMetadata\Peer\ChaincodeShim::initOnce();
        parent::__construct();
    }

    /**
     * <code>string key = 1;</code>
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * <code>string key = 1;</code>
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;
    }

    /**
     * <code>bytes value = 2;</code>
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * <code>bytes value = 2;</code>
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->value = $var;
    }

}

