<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/chaincode_shim.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>protos.QueryResponse</code>
 */
class QueryResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .protos.QueryResultBytes results = 1;</code>
     */
    private $results;
    /**
     * <code>bool has_more = 2;</code>
     */
    private $has_more = false;
    /**
     * <code>string id = 3;</code>
     */
    private $id = '';

    public function __construct() {
        \GPBMetadata\Peer\ChaincodeShim::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .protos.QueryResultBytes results = 1;</code>
     */
    public function getResults()
    {
        return $this->results;
    }

    /**
     * <code>repeated .protos.QueryResultBytes results = 1;</code>
     */
    public function setResults(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\QueryResultBytes::class);
        $this->results = $arr;
    }

    /**
     * <code>bool has_more = 2;</code>
     */
    public function getHasMore()
    {
        return $this->has_more;
    }

    /**
     * <code>bool has_more = 2;</code>
     */
    public function setHasMore($var)
    {
        GPBUtil::checkBool($var);
        $this->has_more = $var;
    }

    /**
     * <code>string id = 3;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <code>string id = 3;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;
    }

}

