<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/admin.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>protos.ServerStatus</code>
 */
class ServerStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.protos.ServerStatus.StatusCode status = 1;</code>
     */
    private $status = 0;

    public function __construct() {
        \GPBMetadata\Peer\Admin::initOnce();
        parent::__construct();
    }

    /**
     * <code>.protos.ServerStatus.StatusCode status = 1;</code>
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * <code>.protos.ServerStatus.StatusCode status = 1;</code>
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Protos\ServerStatus_StatusCode::class);
        $this->status = $var;
    }

}

