<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/events.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * SignedEvent is used for any communication between consumer and producer
 * </pre>
 *
 * Protobuf type <code>protos.SignedEvent</code>
 */
class SignedEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Signature over the event bytes
     * </pre>
     *
     * <code>bytes signature = 1;</code>
     */
    private $signature = '';
    /**
     * <pre>
     * Marshal of Event object
     * </pre>
     *
     * <code>bytes eventBytes = 2;</code>
     */
    private $eventBytes = '';

    public function __construct() {
        \GPBMetadata\Peer\Events::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Signature over the event bytes
     * </pre>
     *
     * <code>bytes signature = 1;</code>
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * <pre>
     * Signature over the event bytes
     * </pre>
     *
     * <code>bytes signature = 1;</code>
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->signature = $var;
    }

    /**
     * <pre>
     * Marshal of Event object
     * </pre>
     *
     * <code>bytes eventBytes = 2;</code>
     */
    public function getEventBytes()
    {
        return $this->eventBytes;
    }

    /**
     * <pre>
     * Marshal of Event object
     * </pre>
     *
     * <code>bytes eventBytes = 2;</code>
     */
    public function setEventBytes($var)
    {
        GPBUtil::checkString($var, False);
        $this->eventBytes = $var;
    }

}

