<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/transaction.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * This message is necessary to facilitate the verification of the signature
 * (in the signature field) over the bytes of the transaction (in the
 * transactionBytes field).
 * </pre>
 *
 * Protobuf type <code>protos.SignedTransaction</code>
 */
class SignedTransaction extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The bytes of the Transaction. NDD
     * </pre>
     *
     * <code>bytes transaction_bytes = 1;</code>
     */
    private $transaction_bytes = '';
    /**
     * <pre>
     * Signature of the transactionBytes The public key of the signature is in
     * the header field of TransactionAction There might be multiple
     * TransactionAction, so multiple headers, but there should be same
     * transactor identity (cert) in all headers
     * </pre>
     *
     * <code>bytes signature = 2;</code>
     */
    private $signature = '';

    public function __construct() {
        \GPBMetadata\Peer\Transaction::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The bytes of the Transaction. NDD
     * </pre>
     *
     * <code>bytes transaction_bytes = 1;</code>
     */
    public function getTransactionBytes()
    {
        return $this->transaction_bytes;
    }

    /**
     * <pre>
     * The bytes of the Transaction. NDD
     * </pre>
     *
     * <code>bytes transaction_bytes = 1;</code>
     */
    public function setTransactionBytes($var)
    {
        GPBUtil::checkString($var, False);
        $this->transaction_bytes = $var;
    }

    /**
     * <pre>
     * Signature of the transactionBytes The public key of the signature is in
     * the header field of TransactionAction There might be multiple
     * TransactionAction, so multiple headers, but there should be same
     * transactor identity (cert) in all headers
     * </pre>
     *
     * <code>bytes signature = 2;</code>
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * <pre>
     * Signature of the transactionBytes The public key of the signature is in
     * the header field of TransactionAction There might be multiple
     * TransactionAction, so multiple headers, but there should be same
     * transactor identity (cert) in all headers
     * </pre>
     *
     * <code>bytes signature = 2;</code>
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->signature = $var;
    }

}

