<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/events.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 *---------- producer events ---------
 * </pre>
 *
 * Protobuf type <code>protos.Unregister</code>
 */
class Unregister extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .protos.Interest events = 1;</code>
     */
    private $events;

    public function __construct() {
        \GPBMetadata\Peer\Events::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .protos.Interest events = 1;</code>
     */
    public function getEvents()
    {
        return $this->events;
    }

    /**
     * <code>repeated .protos.Interest events = 1;</code>
     */
    public function setEvents(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\Interest::class);
        $this->events = $arr;
    }

}

