<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/configuration.proto

namespace GPBMetadata\Common;

class Configuration
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a92020a1a636f6d6d6f6e2f636f6e66696775726174696f6e2e70726f74" .
            "6f1206636f6d6d6f6e22200a1048617368696e67416c676f726974686d12" .
            "0c0a046e616d65180120012809222a0a19426c6f636b4461746148617368" .
            "696e67537472756374757265120d0a05776964746818012001280d22250a" .
            "104f72646572657241646472657373657312110a09616464726573736573" .
            "180120032809221a0a0a436f6e736f727469756d120c0a046e616d651801" .
            "2001280942530a246f72672e68797065726c65646765722e666162726963" .
            "2e70726f746f732e636f6d6d6f6e5a2b6769746875622e636f6d2f687970" .
            "65726c65646765722f6661627269632f70726f746f732f636f6d6d6f6e62" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

