<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msp/msp_config.proto

namespace Msp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * FabricMSPConfig collects all the configuration information for
 * a Fabric MSP.
 * Here we assume a default certificate validation policy, where
 * any certificate signed by any of the listed rootCA certs would
 * be considered as valid under this MSP.
 * This MSP may or may not come with a signing identity. If it does,
 * it can also issue signing identities. If it does not, it can only
 * be used to validate and verify certificates.
 * </pre>
 *
 * Protobuf type <code>msp.FabricMSPConfig</code>
 */
class FabricMSPConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Name holds the identifier of the MSP; MSP identifier
     * is chosen by the application that governs this MSP.
     * For example, and assuming the default implementation of MSP,
     * that is X.509-based and considers a single Issuer,
     * this can refer to the Subject OU field or the Issuer OU field.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * <pre>
     * List of root certificates trusted by this MSP
     * they are used upon certificate validation (see
     * comment for IntermediateCerts below)
     * </pre>
     *
     * <code>repeated bytes root_certs = 2;</code>
     */
    private $root_certs;
    /**
     * <pre>
     * List of intermediate certificates trusted by this MSP;
     * they are used upon certificate validation as follows:
     * validation attempts to build a path from the certificate
     * to be validated (which is at one end of the path) and
     * one of the certs in the RootCerts field (which is at
     * the other end of the path). If the path is longer than
     * 2, certificates in the middle are searched within the
     * IntermediateCerts pool
     * </pre>
     *
     * <code>repeated bytes intermediate_certs = 3;</code>
     */
    private $intermediate_certs;
    /**
     * <pre>
     * Identity denoting the administrator of this MSP
     * </pre>
     *
     * <code>repeated bytes admins = 4;</code>
     */
    private $admins;
    /**
     * <pre>
     * Identity revocation list
     * </pre>
     *
     * <code>repeated bytes revocation_list = 5;</code>
     */
    private $revocation_list;
    /**
     * <pre>
     * SigningIdentity holds information on the signing identity
     * this peer is to use, and which is to be imported by the
     * MSP defined before
     * </pre>
     *
     * <code>.msp.SigningIdentityInfo signing_identity = 6;</code>
     */
    private $signing_identity = null;
    /**
     * <pre>
     * OrganizationalUnitIdentifiers holds one or more
     * fabric organizational unit identifiers that belong to
     * this MSP configuration
     * </pre>
     *
     * <code>repeated .msp.FabricOUIdentifier organizational_unit_identifiers = 7;</code>
     */
    private $organizational_unit_identifiers;
    /**
     * <pre>
     * FabricCryptoConfig contains the configuration parameters
     * for the cryptographic algorithms used by this MSP
     * </pre>
     *
     * <code>.msp.FabricCryptoConfig crypto_config = 8;</code>
     */
    private $crypto_config = null;

    public function __construct() {
        \GPBMetadata\Msp\MspConfig::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Name holds the identifier of the MSP; MSP identifier
     * is chosen by the application that governs this MSP.
     * For example, and assuming the default implementation of MSP,
     * that is X.509-based and considers a single Issuer,
     * this can refer to the Subject OU field or the Issuer OU field.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <pre>
     * Name holds the identifier of the MSP; MSP identifier
     * is chosen by the application that governs this MSP.
     * For example, and assuming the default implementation of MSP,
     * that is X.509-based and considers a single Issuer,
     * this can refer to the Subject OU field or the Issuer OU field.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <pre>
     * List of root certificates trusted by this MSP
     * they are used upon certificate validation (see
     * comment for IntermediateCerts below)
     * </pre>
     *
     * <code>repeated bytes root_certs = 2;</code>
     */
    public function getRootCerts()
    {
        return $this->root_certs;
    }

    /**
     * <pre>
     * List of root certificates trusted by this MSP
     * they are used upon certificate validation (see
     * comment for IntermediateCerts below)
     * </pre>
     *
     * <code>repeated bytes root_certs = 2;</code>
     */
    public function setRootCerts(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->root_certs = $arr;
    }

    /**
     * <pre>
     * List of intermediate certificates trusted by this MSP;
     * they are used upon certificate validation as follows:
     * validation attempts to build a path from the certificate
     * to be validated (which is at one end of the path) and
     * one of the certs in the RootCerts field (which is at
     * the other end of the path). If the path is longer than
     * 2, certificates in the middle are searched within the
     * IntermediateCerts pool
     * </pre>
     *
     * <code>repeated bytes intermediate_certs = 3;</code>
     */
    public function getIntermediateCerts()
    {
        return $this->intermediate_certs;
    }

    /**
     * <pre>
     * List of intermediate certificates trusted by this MSP;
     * they are used upon certificate validation as follows:
     * validation attempts to build a path from the certificate
     * to be validated (which is at one end of the path) and
     * one of the certs in the RootCerts field (which is at
     * the other end of the path). If the path is longer than
     * 2, certificates in the middle are searched within the
     * IntermediateCerts pool
     * </pre>
     *
     * <code>repeated bytes intermediate_certs = 3;</code>
     */
    public function setIntermediateCerts(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->intermediate_certs = $arr;
    }

    /**
     * <pre>
     * Identity denoting the administrator of this MSP
     * </pre>
     *
     * <code>repeated bytes admins = 4;</code>
     */
    public function getAdmins()
    {
        return $this->admins;
    }

    /**
     * <pre>
     * Identity denoting the administrator of this MSP
     * </pre>
     *
     * <code>repeated bytes admins = 4;</code>
     */
    public function setAdmins(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->admins = $arr;
    }

    /**
     * <pre>
     * Identity revocation list
     * </pre>
     *
     * <code>repeated bytes revocation_list = 5;</code>
     */
    public function getRevocationList()
    {
        return $this->revocation_list;
    }

    /**
     * <pre>
     * Identity revocation list
     * </pre>
     *
     * <code>repeated bytes revocation_list = 5;</code>
     */
    public function setRevocationList(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->revocation_list = $arr;
    }

    /**
     * <pre>
     * SigningIdentity holds information on the signing identity
     * this peer is to use, and which is to be imported by the
     * MSP defined before
     * </pre>
     *
     * <code>.msp.SigningIdentityInfo signing_identity = 6;</code>
     */
    public function getSigningIdentity()
    {
        return $this->signing_identity;
    }

    /**
     * <pre>
     * SigningIdentity holds information on the signing identity
     * this peer is to use, and which is to be imported by the
     * MSP defined before
     * </pre>
     *
     * <code>.msp.SigningIdentityInfo signing_identity = 6;</code>
     */
    public function setSigningIdentity(&$var)
    {
        GPBUtil::checkMessage($var, \Msp\SigningIdentityInfo::class);
        $this->signing_identity = $var;
    }

    /**
     * <pre>
     * OrganizationalUnitIdentifiers holds one or more
     * fabric organizational unit identifiers that belong to
     * this MSP configuration
     * </pre>
     *
     * <code>repeated .msp.FabricOUIdentifier organizational_unit_identifiers = 7;</code>
     */
    public function getOrganizationalUnitIdentifiers()
    {
        return $this->organizational_unit_identifiers;
    }

    /**
     * <pre>
     * OrganizationalUnitIdentifiers holds one or more
     * fabric organizational unit identifiers that belong to
     * this MSP configuration
     * </pre>
     *
     * <code>repeated .msp.FabricOUIdentifier organizational_unit_identifiers = 7;</code>
     */
    public function setOrganizationalUnitIdentifiers(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Msp\FabricOUIdentifier::class);
        $this->organizational_unit_identifiers = $arr;
    }

    /**
     * <pre>
     * FabricCryptoConfig contains the configuration parameters
     * for the cryptographic algorithms used by this MSP
     * </pre>
     *
     * <code>.msp.FabricCryptoConfig crypto_config = 8;</code>
     */
    public function getCryptoConfig()
    {
        return $this->crypto_config;
    }

    /**
     * <pre>
     * FabricCryptoConfig contains the configuration parameters
     * for the cryptographic algorithms used by this MSP
     * </pre>
     *
     * <code>.msp.FabricCryptoConfig crypto_config = 8;</code>
     */
    public function setCryptoConfig(&$var)
    {
        GPBUtil::checkMessage($var, \Msp\FabricCryptoConfig::class);
        $this->crypto_config = $var;
    }

}

