<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msp/msp_config.proto

namespace Msp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * MSPConfig collects all the configuration information for
 * an MSP. The Config field should be unmarshalled in a way
 * that depends on the Type
 * </pre>
 *
 * Protobuf type <code>msp.MSPConfig</code>
 */
class MSPConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Type holds the type of the MSP; the default one would
     * be of type FABRIC implementing an X.509 based provider
     * </pre>
     *
     * <code>int32 type = 1;</code>
     */
    private $type = 0;
    /**
     * <pre>
     * Config is MSP dependent configuration info
     * </pre>
     *
     * <code>bytes config = 2;</code>
     */
    private $config = '';

    public function __construct() {
        \GPBMetadata\Msp\MspConfig::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Type holds the type of the MSP; the default one would
     * be of type FABRIC implementing an X.509 based provider
     * </pre>
     *
     * <code>int32 type = 1;</code>
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * <pre>
     * Type holds the type of the MSP; the default one would
     * be of type FABRIC implementing an X.509 based provider
     * </pre>
     *
     * <code>int32 type = 1;</code>
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->type = $var;
    }

    /**
     * <pre>
     * Config is MSP dependent configuration info
     * </pre>
     *
     * <code>bytes config = 2;</code>
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * <pre>
     * Config is MSP dependent configuration info
     * </pre>
     *
     * <code>bytes config = 2;</code>
     */
    public function setConfig($var)
    {
        GPBUtil::checkString($var, False);
        $this->config = $var;
    }

}

