<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orderer/configuration.proto

namespace Orderer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>orderer.BatchTimeout</code>
 */
class BatchTimeout extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Any duration string parseable by ParseDuration():
     * https://golang.org/pkg/time/#ParseDuration
     * </pre>
     *
     * <code>string timeout = 1;</code>
     */
    private $timeout = '';

    public function __construct() {
        \GPBMetadata\Orderer\Configuration::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Any duration string parseable by ParseDuration():
     * https://golang.org/pkg/time/#ParseDuration
     * </pre>
     *
     * <code>string timeout = 1;</code>
     */
    public function getTimeout()
    {
        return $this->timeout;
    }

    /**
     * <pre>
     * Any duration string parseable by ParseDuration():
     * https://golang.org/pkg/time/#ParseDuration
     * </pre>
     *
     * <code>string timeout = 1;</code>
     */
    public function setTimeout($var)
    {
        GPBUtil::checkString($var, True);
        $this->timeout = $var;
    }

}

