<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orderer/configuration.proto

namespace Orderer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * ChannelRestrictions is the mssage which conveys restrictions on channel creation for an orderer
 * </pre>
 *
 * Protobuf type <code>orderer.ChannelRestrictions</code>
 */
class ChannelRestrictions extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The max count of channels to allow to be created, a value of 0 indicates no limit
     * </pre>
     *
     * <code>uint64 max_count = 1;</code>
     */
    private $max_count = 0;

    public function __construct() {
        \GPBMetadata\Orderer\Configuration::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The max count of channels to allow to be created, a value of 0 indicates no limit
     * </pre>
     *
     * <code>uint64 max_count = 1;</code>
     */
    public function getMaxCount()
    {
        return $this->max_count;
    }

    /**
     * <pre>
     * The max count of channels to allow to be created, a value of 0 indicates no limit
     * </pre>
     *
     * <code>uint64 max_count = 1;</code>
     */
    public function setMaxCount($var)
    {
        GPBUtil::checkUint64($var);
        $this->max_count = $var;
    }

}

