<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orderer/ab.proto

namespace Orderer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>orderer.SeekSpecified</code>
 */
class SeekSpecified extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>uint64 number = 1;</code>
     */
    private $number = 0;

    public function __construct() {
        \GPBMetadata\Orderer\Ab::initOnce();
        parent::__construct();
    }

    /**
     * <code>uint64 number = 1;</code>
     */
    public function getNumber()
    {
        return $this->number;
    }

    /**
     * <code>uint64 number = 1;</code>
     */
    public function setNumber($var)
    {
        GPBUtil::checkUint64($var);
        $this->number = $var;
    }

}

