<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orderer/ab.proto

namespace Orderer;

/**
 * Protobuf enum <code>orderer.SeekInfo.SeekBehavior</code>
 */
class SeekInfo_SeekBehavior
{
    /**
     * <code>BLOCK_UNTIL_READY = 0;</code>
     */
    const BLOCK_UNTIL_READY = 0;
    /**
     * <code>FAIL_IF_NOT_READY = 1;</code>
     */
    const FAIL_IF_NOT_READY = 1;
}

