<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orderer/ab.proto

namespace Orderer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>orderer.SeekPosition</code>
 */
class SeekPosition extends \Google\Protobuf\Internal\Message
{
    protected $Type;

    public function __construct() {
        \GPBMetadata\Orderer\Ab::initOnce();
        parent::__construct();
    }

    /**
     * <code>.orderer.SeekNewest newest = 1;</code>
     */
    public function getNewest()
    {
        return $this->readOneof(1);
    }

    /**
     * <code>.orderer.SeekNewest newest = 1;</code>
     */
    public function setNewest(&$var)
    {
        GPBUtil::checkMessage($var, \Orderer\SeekNewest::class);
        $this->writeOneof(1, $var);
    }

    /**
     * <code>.orderer.SeekOldest oldest = 2;</code>
     */
    public function getOldest()
    {
        return $this->readOneof(2);
    }

    /**
     * <code>.orderer.SeekOldest oldest = 2;</code>
     */
    public function setOldest(&$var)
    {
        GPBUtil::checkMessage($var, \Orderer\SeekOldest::class);
        $this->writeOneof(2, $var);
    }

    /**
     * <code>.orderer.SeekSpecified specified = 3;</code>
     */
    public function getSpecified()
    {
        return $this->readOneof(3);
    }

    /**
     * <code>.orderer.SeekSpecified specified = 3;</code>
     */
    public function setSpecified(&$var)
    {
        GPBUtil::checkMessage($var, \Orderer\SeekSpecified::class);
        $this->writeOneof(3, $var);
    }

    public function getType()
    {
        return $this->whichOneof("Type");
    }

}

